name: app_b
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.3+4

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  app_links: 2.2.2
  audio_service: ^0.18.9
  audiotagger:
    git:
      url: https://github.com/Sangwan5688/Audiotagger
      ref: 90f2db5
  # bitsdojo_window: ^0.1.1+1 #For Desktops
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.5
  dart_des: ^1.0.2
  device_info_plus: ^8.0.0
  file_picker: ^5.2.5
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_archive: ^5.0.0
  flutter_displaymode: ^0.5.0
  # flutter_downloader: ^1.7.1
  flutter_localizations: 
    sdk: flutter
  get_it: ^7.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  just_audio: ^0.9.31
  # Discontinued, Use just_audio_windows instead.
  # just_audio_libwinmedia: ^0.0.4 # For windows and linux.
  logging: ^1.1.1
  marquee: ^2.2.3
  material_design_icons_flutter: 5.0.5955-rc.1
  on_audio_query: ^2.6.1
  package_info_plus: ^3.0.2
  palette_generator: ^0.3.3+2
  path_provider: ^2.0.12
  permission_handler: ^10.2.0
  receive_sharing_intent: ^1.4.5
  salomon_bottom_bar: ^3.3.1
  share_plus: ^6.3.0
  sliding_up_panel: ^2.0.0+1
  supabase: ^1.1.1
  url_launcher: ^6.1.8
  uuid: ^3.0.7
  youtube_explode_dart: ^1.12.3
  # 
  flutter_launcher_icons: ^0.11.0
  audioplayers: ^3.0.1
  
  google_fonts: ^4.0.3
  intl: any
  flutter_islamic_icons: ^1.0.2
  firebase_core: ^2.10.0
  firebase_storage: ^11.1.1
  image_picker: ^0.8.7+3
  


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.PNG"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo.PNG"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logo.PNG"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo.PNG"
    
flutter:
  uses-material-design: true
  
  generate: true

  assets:
    - sound/
    - assets/doa.json
    - assets/1.json
    - assets/36.json
    - assets/logo.PNG
    # - assets/1.mp3
    # - assets/36.mp3

  # - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
