// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbePjgrqKYFD21hchwt91N88gDb5e-q_I',
    appId: '1:262090371607:web:542e836db8ee8218462252',
    messagingSenderId: '262090371607',
    projectId: 'al-fatiha-25bc1',
    authDomain: 'al-fatiha-25bc1.firebaseapp.com',
    storageBucket: 'al-fatiha-25bc1.appspot.com',
    measurementId: 'G-E92QWP0ZY0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbAu610p0PyN52DAp2dLkiE3FNqGXDpWk',
    appId: '1:262090371607:android:f18a3f129b9e2456462252',
    messagingSenderId: '262090371607',
    projectId: 'al-fatiha-25bc1',
    storageBucket: 'al-fatiha-25bc1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt60WHH4GQ57QiS4r07WCkJFTHq-WLfOI',
    appId: '1:262090371607:ios:7d66eaec804df3f0462252',
    messagingSenderId: '262090371607',
    projectId: 'al-fatiha-25bc1',
    storageBucket: 'al-fatiha-25bc1.appspot.com',
    iosClientId: '262090371607-drd8ojbivn933599c1ut0pjo4uvf4mlc.apps.googleusercontent.com',
    iosBundleId: 'com.example.appb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt60WHH4GQ57QiS4r07WCkJFTHq-WLfOI',
    appId: '1:262090371607:ios:7d66eaec804df3f0462252',
    messagingSenderId: '262090371607',
    projectId: 'al-fatiha-25bc1',
    storageBucket: 'al-fatiha-25bc1.appspot.com',
    iosClientId: '262090371607-drd8ojbivn933599c1ut0pjo4uvf4mlc.apps.googleusercontent.com',
    iosBundleId: 'com.example.appb',
  );
}
